env: prod

# Backend configuration
backend_cpu: "1024"
backend_memory: "2048"
backend_desired_count: 2

# Frontend configuration
frontend_cpu: "512"
frontend_memory: "1024"
frontend_desired_count: 2

# Database
aurora_instance_class: db.r6g.large

# Logging
log_level: warning

# Domain
domain_name: lms.tuescuela.edu

# SES
ses_from_email: noreply@lms.tuescuela.edu